name: Test

on:
   workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        echo "working"
